# Generated by Django 4.2 on 2023-04-19 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование резюме')),
                ('vacancy', models.CharField(choices=[('IT', 'IT'), ('Образование', 'Образование'), ('PR', 'PR'), ('Торговля', 'Торговля')], max_length=100, null=True, verbose_name='Профессия')),
                ('sex', models.CharField(choices=[('Мужчина', 'Male'), ('Женщина', 'Female')], max_length=100, null=True, verbose_name='Пол')),
                ('about', models.TextField(blank=True, max_length=3000, null=True, verbose_name='О себе')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Уровень дохода')),
                ('phone', models.CharField(max_length=25, verbose_name='Номер телефона')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытое резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_author', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Компания')),
                ('vacancy', models.CharField(max_length=150, verbose_name='Должность')),
                ('start_date', models.IntegerField(verbose_name='Дата начала работы')),
                ('end_date', models.IntegerField(verbose_name='Дата окончания работы')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='headhunter.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_form', models.CharField(choices=[('Курсы', 'Курсы'), ('Среднее образование', 'Среднее образование'), ('Высшее образование', 'Высшее образование'), ('Без образования', 'Без образования')], max_length=100, null=True, verbose_name='Вид образования')),
                ('education', models.CharField(max_length=150, verbose_name='Место обучения')),
                ('profession', models.CharField(max_length=150, verbose_name='Специальность')),
                ('start_date', models.IntegerField(verbose_name='Дата начала обучения')),
                ('end_date', models.IntegerField(verbose_name='Дата окончания обучения')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='headhunter.resume', verbose_name='Резюме')),
            ],
        ),
    ]
