# Generated by Django 4.2 on 2023-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='vacancy',
            field=models.CharField(choices=[('IT', 'IT'), ('Образование', 'Образование'), ('PR', 'PR'), ('Торговля', 'Торговля')], max_length=100, null=True, verbose_name='Категория'),
        ),
    ]
