# Generated by Django 4.2 on 2023-04-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('headhunter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование вакансии')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание вакансии')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Заработная плата')),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Образование', 'Образование'), ('PR', 'PR'), ('Торговля', 'Торговля')], max_length=30, verbose_name='Сфера деятельности')),
                ('exp_from', models.IntegerField(verbose_name='Стаж от')),
                ('exp_to', models.IntegerField(verbose_name='Стаж до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытое резюме')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_author', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
        ),
    ]
