# Generated by Django 4.2 on 2023-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headhunter', '0003_alter_resume_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin'),
        ),
    ]
